### PR TITLE
Implement ch2.2.3-ex7 (reverse linked list) in Scheme

### PR DESCRIPTION
**Pull request by masak**
Happy to note that I can apparently get a Scheme program to work, and also that it's possible to get fairly close to our imperative/mutating TypeScript solution. Being that mutating might not be idiomatic Scheme, but it's what the exercise calls for.

Also added some README instructions on how to install and use CHICKEN Scheme.

### CODE REVIEW

**Comment by claes-magnus** [comment]
Detta får vänta några dagar. Vill göra ordentligt. Innan visning lär det
inte bli av (dvs. inte innan torsdag).

Ska läsa Bashbok på tåget hem dock! :)

Den mån 8 juli 2019 kl 09:58 skrev Carl Mäsak <notifications@github.com>:

**Comment by masak** [comment]
@claes-magnus Absolutely; no rush.

For when you have time, here's a small reading guide for Scheme (basically what I picked up as I wrote this):

* `define-record`. Comparable to JS's `class` keyword. Defines a new type with a set of fields.
    * `setter` makes a field writeable. (Which is why we can later use `set!` on the field's accessor.)
* `define-record-printer`. Comparable to JS's `toString` method.
* `define` is used to define values and functions. Note that the function name and its arguments are written inside the same set of parentheses in Lisp/Scheme: `(reverse-linked-list lst)` would look like `reverseLinkedList(lst)` in JS. Later, near the end, we're defining a linked list `lst`; the difference between function and value is that the function is written with a parameter list, whereas the value is defined as just a name.
* `let` declares a new variable ("name binding") just like in JS, but also contains the body of code inside which this name binding is active.
* The `let loop` construction is actually a function declaration. The parameters &mdash; here only one &mdash; are initialized with values, and the `loop` invocation later is a tail-recursive call. This is the closest we get to the `for` loop solution in the TypeScript code. (Note: nothing special with the word `loop`; it's not a keyword or anything. It just felt like an appropriate name for the convenience recursive helper function.)
* `and` works like JS's `&&`, and we're using it as a guard here, just like in JS. (We only want to act on a node if we haven't reached the end of the list.)
* `set-cdr!` mutates the cdr part of a [cons cell](https://en.wikipedia.org/wiki/Cons)
* `set!` changes a variable binding or some other binding. In this case we're changing the `first` field of the `lst` record; in JS, we'd have written it as `lst.first = previousNode;`.

**Comment by masak** [comment]
Writing this program, I had the sense that Scheme is very beautiful; serene, even. Not a single breath is wasted. Every movement has a purpose. The language itself is small, but the constituents are very expressive.

**Comment by claes-magnus** [comment]
> Writing this program, I had the sense that Scheme is very beautiful; serene, even. Not a single breath is wasted. Every movement has a purpose. The language itself is small, but the constituents are very expressive.

I love your passion for code, your poetic view on syntax.  Thumbs up.

**Comment by claes-magnus** [comment]
It would strangely inconsistent to say you understood code written in a language very alien to your mother-tongue, even when if it's a programming language, and still say you find it illuminating. But I do, I think. (It helped though to compare this code with the TypeScript, 'imperative' version.) In a sense - I think, you'll need to verify this - it's more explicit, at least when it comes to recursion. And perhaps my main difficulty was the naming of 'loop'.  

At first, I thought 'loop' should've been named 'examine' but then I took a quick look in a [dictionary](https://www.freethesaurus.com/loop) and found a fascinating picture who provided, to me, new meaning on the notion of the loop. I also found [this definition](https://www.thefreedictionary.com/loop):
>>Something having a shape, order, or path of motion that is circular or curved over on itself.

So, I guess the naming what **not** strange. However, I would like to ask you if the connotations may be misleading to a programmer (since it's not an imperative loop, and my guess is this the 'standard' association of most junior programmers)? 

```
...(let loop ((node (linked-list-first lst)))
     ...
         (loop next-node))))
```

### Very humble sugestions
* examine next-node
* traverse next-node
* deepen next-node (???)

Perhaps I'm reading it all wrong. :) But if at first the node is 'examined' and at the end, we 'continue' with 'next-node' and do the same thing, 'examines' it I think the naming of 'loop' perhaps should change so we can clarify that it's a 'recursive' motion. On the other hand, my current, perhaps junior view is that 'recursion'  and the imperative for-ish or while-ish actions are very similiar beside from how conceptualize them. I mean, aren't in a sense a for-loop a 'function' (in a way)? It receives input and returns a output, or at least a side-effect. Not all functions (keyword:ed so in some language) returns 'value(s)'. Isn't the 'motion' more essential here? And in both cases, what's important is the return to modified, 'initial' state until a base case (a condition) ends the 'loop', heh. Ok, it's early in the day and I know I'm on deep waters now so I'd better end... ;) :)

**Comment by masak** [comment]
> It would strangely inconsistent to say you understood code written in a language very alien to your mother-tongue, even when if it's a programming language, and still say you find it illuminating. But I do, I think.

Good! I want to help shape a world where we can all get beyond "aaah parentheses" and look at a deeper, more meaningful structure.

> (It helped though to compare this code with the TypeScript, 'imperative' version.)

One, yes &mdash; this code is an almost _statement-for-statement_ translation of the TS version. Two, this version _is_ imperative, too, in the sense that it mutates state just as much as the TS version. A declarative/functional rendering of the same algorithm would have had no `set!` calls in it. (But you can't both get rid of those and not allocate new objects.)

> In a sense - I think, you'll need to verify this - it's more explicit, at least when it comes to recursion. And perhaps my main difficulty was the naming of 'loop'.
> 
> At first, I thought 'loop' should've been named 'examine' but then I took a quick look in a [dictionary](https://www.freethesaurus.com/loop) and found a fascinating picture who provided, to me, new meaning on the notion of the loop. I also found [this definition](https://www.thefreedictionary.com/loop):
> 
> > > Something having a shape, order, or path of motion that is circular or curved over on itself.
> 
> So, I guess the naming what **not** strange. However, I would like to ask you if the connotations may be misleading to a programmer (since it's not an imperative loop, and my guess is this the 'standard' association of most junior programmers)?
> 
> ```
> ...(let loop ((node (linked-list-first lst)))
>      ...
>          (loop next-node))))
> ```

I see where you're going with this, and I agree with you that naming is important. (Although the dark side of naming discussions is that they risk turning into [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding). We don't need to worry about that here, though.)

I did pause and think about what name to choose. This is an internally named helper, and so the name should be something short and preferably evocative/catchy. I think I considered `go` as an alternative name.

I went with `loop` because it is a loop. This is how you express an imperative "foreach"-type loop over a list in Scheme. Again, the name `loop` is not taken by anything else in the environment. It's not a keyword or an existing procedure or anything. (Although I found out it's defined as a [macro in the CHICKEN test suite](https://code.call-cc.org/cgi-bin/gitweb.cgi?p=chicken-core.git;a=blob;f=tests/loopy-loop.scm;h=dd5a1409fa8d770c21fea7cc3254b019d334871f;hb=HEAD#l58).

Looking for prior art, I found `DOLOOP` on p. 4 of [the paper that introduced Scheme to the world](https://apps.dtic.mil/dtic/tr/fulltext/u2/a030751.pdf), used for much the same purpose (although since this is a proto-version of Scheme rather than R5RS, the authors use `LABELS` instead of a named let).

As for readability, for _me_ `loop` has the intended effect. I read the `(loop next-node)` sexpr as "and now we loop, taking `next-node` as our focus of interest". Crucially, I'm intending `loop` as a verb, not a noun. (In Scheme, since it's in "first position" and therefore used as a procedure, this is implicitly understood.)

In the end, a named `let` is just a convenience that lets us elide a `define` of an internal helper, just so we can tail-recurse back to some given point. I didn't know about named `let` before I wrote this program; I read about it in [R5RS](https://schemers.org/Documents/Standards/R5RS/). But I considered it elegant and "strangely consistent"; it works like a regular `let` (in that you get to declare and bind variables), but it also throws in a "label" along the way.

Another reason I'm happy with `loop` as a name here is that I was trying to copy the TypeScript code, which does have a loop in that position. Calling it `for-loop` in the Scheme version would maybe have been pushing it one step too far; there's no such thing as a `for` loop in Scheme. But calling it a `loop`, somewhat in honor of the code that I was cribbing, felt appropriate.

> ### Very humble suggestions
> 
>     * examine next-node
> 
>     * traverse next-node
> 
>     * deepen next-node (???)

Of those, I think I dislike `examine` the least. :smile:

`traverse` has all the benefits and flaws of `loop`; specifically, it's usually used for the _whole_ structure, not for the individual elements.

`deepen` sounds weird to me. In what sense do we deepen the node we visit?

By the way, `visit` would probably have been an acceptable name choice, reverberating with [the Visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern).

> Perhaps I'm reading it all wrong. :) But if at first the node is 'examined' and at the end, we 'continue' with 'next-node' and do the same thing, 'examines' it I think the naming of 'loop' perhaps should change so we can clarify that it's a 'recursive' motion. On the other hand, my current, perhaps junior view is that 'recursion' and the imperative for-ish or while-ish actions are very similiar beside from how conceptualize them.

In that paper I linked above, an important point the authors want to make is that they are more than "very similar", they are _identical_. They generate the same machine code, because the Scheme compiler notices the tail recursion, sees what's up, and eliminates it, leaving a few `set!` calls and a `goto`.

> I mean, aren't in a sense a for-loop a 'function' (in a way)? It receives input and returns a output, or at least a side-effect. Not all functions (keyword:ed so in some language) returns 'value(s)'. Isn't the 'motion' more essential here? And in both cases, what's important is the return to modified, 'initial' state until a base case (a condition) ends the 'loop', heh. Ok, it's early in the day and I know I'm on deep waters now so I'd better end... ;) :)

I could quibble over the way you're phrasing it, but I like the general thrust of your argument. :smile: Note additionally that in this particular code, we're using recursion but we're not returning a value in the end. (Well, we are, but it's always `'()` because that's how we bottom out of the recursion. And nothing consumes that value, so it's literally irrelevant.) That is, we're only using the recursion for its side effects. Just as one would a `for` loop in JavaScript.

**Comment by masak** [comment]
For what it's worth, I asked on `#chicken` about the name `loop`:

loop-naming-convention

**Pull request merged**
